name: Auto Merge Development to Master

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Merge Development into Master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: master
          github_token: ${{ github.token }}